//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace simpleMvc.Api4
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Book
    {
        [Key]
        public int bookId { get; set; }
        public int? userId { get; set; }
        public string bookTitle { get; set; }
        public string author { get; set; }

        [ForeignKey("userId")]
        public virtual User User { get; set; }
    }
}
