//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace simpleMvc.Api4
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class User
    {
        public User()
        {
            this.Books = new HashSet<Book>();
            //this.UserRoles = new HashSet<UserRole>();
            this.Roles = new HashSet<Role>();
        }


        public int userId { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string passcode { get; set; }
        public string refreshToken { get; set; }

        public ICollection<Book> Books { get; set; }
        [JsonIgnore]
        public ICollection<UserRole> UserRoles { get; set; }
        public ICollection<Role> Roles { get; set; }
    }
}
