//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace simpleMvc.Api5.Websocket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int bookId { get; set; }
        public int? userId { get; set; }
        public string bookTitle { get; set; }
        public string author { get; set; }
    
        public virtual User User { get; set; }
    }
}
